apiVersion: apps/v1
kind: Deployment
metadata:
  name: microshop-carts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: carts
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
        - name: carts
          image: "{{ .Values.carts.image.repository }}:{{ .Values.carts.image.tag }}"
          ports:
            - containerPort: {{ .Values.carts.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: microshop-carts
spec:
  type: {{ .Values.carts.service.type }}
  selector:
    app: carts
  ports:
    - port: {{ .Values.carts.service.port }}
      targetPort: {{ .Values.carts.service.port }}
